project:
  type: book

book:
  title: "Template"
  author: "Maryam"
  date: today
  site-url: https://maryam-nouriaiin.github.io/quarto_book_template/
  repo-url: https://maryam-nouriaiin.github.io/quarto_book_template/
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - First.qmd
    - Second.qmd
    - Third.qmd
page-footer:
  left:
    - icon: envelope
      href: mailto:maryam.nouri-aiin@uvm.edu

    - icon: github
      href: https://github.com/

  center:
    - icon: link
      href: https://www.maryam-nouriaiin.com/

    - icon: instagram
      href: https://www.instagram.com/uvm_ecopestmgmt/

    - icon: graduation-cap
      href: https://scholar.google.com/citations?user=k1I1bOsAAAAJ&hl=en

  right:
    - icon: linkedin
      href: https://www.linkedin.com/in/maryam-nouri-aiin-5b2b00115/

    - icon: orcid
      href: https://orcid.org/0000-0003-4795-7777

    - icon: flask
      href: https://www.researchgate.net/profile/Maryam-Nouri-Aiin-2?ev=hdr_xprf
      
format:
  html:
    theme: [default, style/graphs.scss]
    code-link: true
    highlight-style: style/joyce.theme
    callout-icon: false
    fig-width: 4
    fig-height: 3
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 50%
    
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: false

editor: source

