project:
  type: book

book:
  title: "test"
  author: "Norah Jones"
  date: "3/30/2025"
  chapters:
    - first.qmd
    - second.qmd
    - third.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual


